### ISSUE TITLE
Redesign APIs to accept MaybeUninit

### ISSUE THREAD

**Issue by RReverser** [adamkewley/libdeflater#1]
Currently, all APIs expect a pre-allocated slice for the output data. The problem is, it either requires caller to zero-allocate a vector for such output buffer, or to allocate an uninitialised heap data, which can easily lead to a UB.

In order to avoid the latter, APIs should be able to be called as `(..., &mut [MaybeUninit<u8>]) -> CompressionResult<&[u8]>` instead of the current `(..., &mut [u8]) -> CompressionResult<usize>` so that the caller wouldn't have to mark uninitialised data as ready-to-use, and would safely get the initialised part of the slice back and not the whole thing.

**Comment by adamkewley** [comment]
Hi @RReverser , 

I'm very sorry I didn't get back to you. I've been very busy recently with a bunch of unrelated life stuff and I think that this issue was buried in my inbox, so I didn't notice it. This is my fault.

I think that your suggestion is a good one. I've never heard of `MaybeUninit` before, so this was a great opportunity to read into it. I have had a (very very quick) go at throwing an implementation of this on a branch to see how it feels (see above).

Overall, I think this might be an improvement, but there's a few things I'd like your input on:

- Is the resulting API going to be obvious to typical Rust devs? My concern is that it's not immediately obvious that the slice returned by the function call is aligned with the start of the slice provided to the function. The lifetype signature implies that the returned slice is certainly a subslice of the argument, but how's best for me to articulate that the returned slice has a 0-offset from the provided one? The reason this is significant is because callers might want to resize (e.g.) a `Vec` externally after receiving the return value

- What's the cleanest way to cast a `Vec<u8>` to `[MaybeUninit<u8>]`? The non-`MaybeUninit<T>` equivalent is easy because a `Vec<T>` can be implicitly converted into a slice.

On top of these concerns, the big thing preventing me from implementing this right now is that it's going to be an API break. This is an under-used library, so that's probably not as big of a deal, but I *really* don't like breaking APIs unless there's a clear improvement in stability, readability, or performance because it requires redoing all the tests, documentation, benchmarks, and finding the 2 people using this in the wild. 

Because of that, I'd *personally* prefer to keep this on a back-burner until there's enough people using the API, or showing their dissatisfaction, or there's enough other API changes queued up such that that I can roll all of the breaking changes into one atomic API break and perform a major version bump. Imho, devs typically hate when a library makes loads of little breaking changes regularly - especially the kind of devs who want to dump this library into their backends and never touch it again (most system-level libraries in a nutshell).

**Comment by RReverser** [comment]
> I'm very sorry I didn't get back to you.

No worries, that's understandable.



> I've never heard of `MaybeUninit` before, so this was a great opportunity to read into it.

To be fair, it's quite a recent addition.

Basically, before this Rust didn't have a good model for uninitialized values and used `mem::uninitialized` for creating blocks of data without an initialized value, and allowed to pass mutable references to them as to any other.

However, this is one of places that presented a major soundness hole, was very easy to misuse, and to trigger UB - first, by accidentally reading such data, and second by creating a reference to uninitialized data (as opposed to a raw pointer) in the first place - both of these are UB from the language perspective, so all bets are off.

There have been a long discussion around ways to fix this hole, and this is how `MaybeUninit` came to be, `mem::uninitialized` got deprecated, and now there is an ongoing effort to eradicate any incorrect usages of referenced to uninitialized data in standard library and 3rd-party APIs.

This library caught my eye as part of https://rreverser.com/bringing-oxipng-to-squoosh/, and, exactly because it's somewhat underused at the moment, it seems like a good time to fixup the API and bump a major version (I'll be sure to upgrade on the Squoosh side).

You mentioned

> unless there's a clear improvement in stability

so hopefully the explanation above sheds some light on importance of such fixes from stability perspective.

---

As for the specific API questions, I'll need to take a look slightly later and will try to get back to you (please feel free to ping me if you don't hear from me in a few days :) ).

**Comment by vlisivka** [comment]
Why not just accept empty vec, and then set it length using unsafe `Vec::set_len(len)`?
```
            let ret: libdeflate_result =
                libdeflate_gzip_decompress(self.p,
                                           in_ptr,
                                           gz_data.len(),
                                           out_ptr,
                                           out.capacity(),
                                           &mut out_nbytes);
            match ret {
                libdeflate_result_LIBDEFLATE_SUCCESS => {
                    unsafe { out.set_len(out_nbytes); }
                    Ok(out_nbytes)
                },

```

**Comment by adamkewley** [comment]
@vlisivka , your reply slipped through my emails - sorry.

The reason why I would avoid using a `Vec` is because that would constrain the implementation to *have* to write to a `Vec`.

Although that's probably sane for most APIs, it might be sub-optimal for the demograph of users who are integrating something as low-level as `libdeflater`. `libdeflater` is targeted at low-level integrations where:

- There's a significant enough (de)compression throughput problem to merit using something non-standard (e.g. `flate`)
- The data is well-understood enough to work around the benefits/pitfalls of using a non-streaming, SIMD-optimized compression library (`libdeflate`)
- E.g. high-thoughput genomic (de)compression, game netcode (where packets might be pre-sliced), embedded, etc.

Purely a guess, but the type of devs that work at that low-level are "power tools" systems developers that will feasibly also be using things like custom allocators, stack allocators for smaller buffers, and object pools. None of which would be possible if the lowest-level API (`libdeflater`) required a heap-allocated `Vec`.

**Comment by adamkewley** [comment]
Closing this because, while I agree with the request, I don't think it's worth breaking any existing API to do so, nor is it worth adding an auxiliary "overloaded" API (probably suffixed) to add this.

I've kept this open for a year or so in case other devs are screaming for this, but I don't get the impression that this API wart a big enough deal to discourage lower-level system devs from integrating the library.
