### ISSUE TITLE
license file is not in the crate source

### ISSUE THREAD

**Issue by remilauzier** [adamkewley/libdeflater#12]
Hi! i am packaging your library for fedora. Fedora project prefer to have a copy of the license include in the source. Here the link to the fedora guideline.
https://docs.fedoraproject.org/en-US/packaging-guidelines/LicensingGuidelines/#_license_text

It should just be a mater of an ``include = "LICENSE, README.md, etc"``
Thanks for your time.

**Comment by adamkewley** [comment]
Hi @remilauzier , I'm not quite sure what you require, based on that link.

As stated in it:

> If the source package includes the text of the license(s) in its own file, then that file, containing the text of the license(s) for the package must be included in %license. If the source package does not include the text of the license(s), the packager should contact upstream and encourage them to correct this mistake.

Which, for this repo, is the LICENSE file:

https://github.com/adamkewley/libdeflater/blob/master/LICENSE

And for Rust packaging, there's the `license` field in `Cargo.toml`, which matches:

https://github.com/adamkewley/libdeflater/blob/master/Cargo.toml#L6

The Fedora guidelines also state:

> It is important to reiterate that in situations where the indicated license does not imply a requirement that the license be distributed along with the source/binaries, Fedora packagers are NOT required to manually include the full license text when it is absent from the source code. but are still encouraged to point out this issue to upstream and encourage them to remedy it.

So it may not even be a requirement to write the license into the resulting binary/library. I'm unfamiliar with Fedora packaging for Rust (I'm primarily a C++ dev who uses something like `fpm`). I'm guessing that adding something like:

```
[[package]
# ...
include = ["src/**/*", "Cargo.toml"]
```

As described [here](https://doc.rust-lang.org/cargo/reference/manifest.html#the-exclude-and-include-fields) is ok? Does that provide your packaging toolchain with enough information to produce a Fedora package? If so, I can add that fairly easily if you'd like.

**Comment by remilauzier** [comment]
Hi @adamkewley, the source package in this case is the source publish on crates.io.

Fedora prefer having the license file in the crate source to put it after in ``/usr/share/licenses/nameoftheprogram``.
For now it extract the metadata with ``cargo.toml`` to put it in the .spec file but it doesn't create a copy of the license file it need.
here an exemple: https://github.com/jmesmon/rust-systemd/pull/192
https://src.fedoraproject.org/rpms/rust-systemd/blob/rawhide/f/rust-systemd.spec

you can see that fedora extract it from github for now because it wasn't include in the crate source from crates.io.
``include = ["src/**/*", "Cargo.toml", "README.md","LICENSE"]`` should do the tricks.
if you have more question that need better answer @eclipseo has better experience with rust then me.

**Comment by adamkewley** [comment]
@remilauzier I've looked into this and I *believe* the problem you're having is specifically with `libdeflate-sys`, not `libdeflater`.

The crate contents for `libdeflater` in `master` does include `LICENSE`:

```text
ls -1 target/package/libdeflater-0.7.1
bench_data
benches
Cargo.lock
Cargo.toml
Cargo.toml.orig
examples
LICENSE
README.md
scripts
src
target
tests
```

Whereas `libdeflate-sys` does not have its own LICENSE file:

```text
ls -1 target/package/libdeflate-sys-0.7.1
build.rs
Cargo.toml
Cargo.toml.orig
libdeflate
README.md
src
target
```

This *could* be amended by adding an `include` key to `Cargo.toml`, but that comes with its own pitfalls. Namely, that it makes `cargo` **only** include what's in the `include` field, which also requires explicitly including things like `benches/` and `libdeflate-sys/libdeflate` etc. to get a clean build working. 

Ultimately, this would just be extra noise in `Cargo.toml` which, by default, includes everything in the source tree. I *think* (please confirm) the solution here is to just copy `LICENSE` into `libdeflate-sys` so that it ends up in the resulting crate. 

After that copy, plus a version bump, the contents are now:

```text
ls -1 target/package/libdeflate-sys-0.7.2
build.rs
Cargo.toml
Cargo.toml.orig
libdeflate
LICENSE
README.md
src
target
```

I'll go and merge the LICENSE copy, because it's probably a sane thing to do. If that's enough, I can close this. Otherwise, please clarify what you need for Fedora packaging specifically. I work on various projects and don't have enough time to carefully read through each distro's requirements, so any links/quotes/contacts that can clearly explain Rust packaging in Fedora would be welcome.

**Comment by remilauzier** [comment]
Hi @adamkewley
Thanks that exactly the thing i need. Fedora just need a copy of the license in the crate source. if you need more info on fedora @eclipseo will be better then me to answer.

**Comment by adamkewley** [comment]
Hi @remilauzier 

I know this has taken a while--many other things going on :<--but 0.7.3, which is now up on cargo, should contain the added LICENSE!

**Comment by remilauzier** [comment]
Thanks!

**Comment by remilauzier** [comment]
It seem that libdeflate-sys doesn't have the license include.

**Comment by remilauzier** [comment]
Forget what i said. i was checking 0.7.2. Thanks for your work.

**Comment by adamkewley** [comment]
Out of interest, is this enough to automatically package it on Fedora now? Just so I know for future crates (if I ever get the time! :))

**Comment by remilauzier** [comment]
Yes. it is enough. lbdeflater is now on fedora. https://src.fedoraproject.org/rpms/rust-libdeflater
