### ISSUE TITLE
Suggestion: Add Vec<u8> compression and decompression functions

### ISSUE THREAD

**Issue by AronParker** [adamkewley/libdeflater#19]
As it stands right now all functions take a mutable slice as output:

```rust
    pub fn gzip_decompress(&mut self, gz_data: &[u8], out: &mut [u8]) -> DecompressionResult<usize>
```

This requires initializing `out` with some value even though it is exclusively written to by the compressor. (Ab)using [slice::from_raw_parts_mut](https://doc.rust-lang.org/core/slice/fn.from_raw_parts_mut.html#) does not work as it requires its elements to be "properly initialized".

I would suggest adding an API as follows:

```rust
    pub fn gzip_decompress_vec(&mut self, gz_data: &[u8], out: &mut Vec<u8>) -> DecompressionResult<usize>
```

This would use the spare unused capacity of the `Vec<u8>` to compress into and update its `len` on success.

**Comment by adamkewley** [comment]
Does "properly initialized" *require* "zero initialized", in Rust nomenclature? Because it's *very* commonplace to pass a slice-like concept into (e.g.) a C API. Fundamentally, the underlying datatype (`u8`) fulfills all of its (type-level) invariants regardless of its initial value (`0x00-0xff`). It would be undefined behavior if this wasn't the case (e.g. if one was initializing a range of objects that contain pointers from a raw memory allocation), and there's `MaybeUninit` to *officially* handle that, but there hasn't been a particularly large outcry to break the API to support that.

I believe that an efficient implementation of your proposed `gzip_decompress_vec` function would effectively need to combine:

1) [reserve](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.reserve)
2) [as_mut_ptr](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.as_mut_ptr)
3) (effectively, create a slice from the pointer + uninitialized parts in order to call into `libdeflate` here)
4) [set_len](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.set_len)

`libdeflater` currently provides the nuts-and-bolts of step `3` and assumes the caller is better-equipped to handle steps `1`, `2`, and `4`. This is because we assume the caller will know more about the context in which (de)compression is happening.

It might be nice to provide a convenience API that effectively does those steps internally. However, doing so would require doubling quite a few functions+tests+documentation. For the sake of providing a convenience API for one collection class (`Vec`) I'm unsure if that's worth the payoff - especially given that this is a fairly low-level library where the developers are likely to know what/why they're using `libdeflate`.

I'd be open to someone PRing the functionality, but if someone's interested, please ensure:

- It's uniform for all of the library methods (there can't be a convenience function for one part of the API, all suitable API functions must provide an equivalent convenience)
- It needs basic tests
- It needs documentation (e.g. caller guarantees, callee guarantees around allocations, etc.)
