### ISSUE TITLE
Rename crate to libdeflate-sys?

### ISSUE THREAD

**Issue by brainstorm** [adamkewley/libdeflater#2]
It took me a bit to find this one since it doesn't seem to follow the "the facto" naming convention for `-sys` crates? Not high priority mind you, just noting it ;)

**Comment by adamkewley** [comment]
@brainstorm I see what you mean--and my earlier internal versions of this crate did do this--but I ultimately didn't name this crate with `-sys` because (IIRC):

- This crate doesn't expose the raw FFI bindings to `libdeflate`. Internally, I'm wrapping the C API with this crate, but you can't use this crate to get the C bindings. Similar crates, such as [flate2](https://github.com/alexcrichton/flate2-rs) by @alexcrichton seem to also publish (e.g.) [miniz-sys](https://github.com/alexcrichton/flate2-rs/tree/master/miniz-sys) to encapsulate *just* the FFI bindings. A `-sys` crate usually only contains `unsafe` C bindings that downstream devs then need to wrap. I might be wrong here, and need confirmation: I'm only basing that assertion on the handful of crates I've seen in the wild.

- I'm not the author of `libdeflate`, @ebiggers is. I didn't want to "steal" the standard crate names because I didn't ask the original author whether it would be OK for me to write the official Rust bindings to libdeflate. @ebiggers might've wanted to write his own, or get another developer to write it, or hate my guts. Either way, I felt it would've been a dick move to name a crate exactly the same as someone else's project, so I put a mild "spin" on the original name (+r) to at least make people think that something unofficial might be going on.

These probably aren't great reasons. I could maybe put the FFI level of this library, which is entirely contained in [this](https://github.com/adamkewley/libdeflater/blob/master/src/libdeflate_sys.rs) source file into its own crate called `libdeflate-sys`, in case people want to write their own FFI. I thought about doing this at the time, but I figured that if people aren't interested in the Rust library then it's unlikely that people would be interested in the system-level bindings. Also, it would've taken me an extra session or two to publish it, because I personally don't ship things without some basic test coverage + docs (like the Rust wrapper), so I just interned the `-sys` stuff and left it internal.

**Comment by adamkewley** [comment]
@pmarks helpfully found the related doc about crate naming:

https://doc.rust-lang.org/cargo/reference/build-scripts.html#-sys-packages

So I don't think it's accurate to call this a `-sys` crate because it provides Rust bindings over the FFI. However, it would probably be an idea for me to publish `libdeflater-sys` at least (not `libdeflate-sys` because, again, imho `libdeflate` is someone else's baby).

**Comment by brainstorm** [comment]
Makes a ton of sense, thanks for elaborating so much on this :)
