### ISSUE TITLE
Initialize decompressor for random access

### ISSUE THREAD

**Issue by gauteh** [adamkewley/libdeflater#20]
Hi,

is it possible to initialize the decompressor so that it can be used for random access to compressed data (given indexed initialization data): https://github.com/madler/zlib/blob/master/examples/zran.c

We're using libdeflater in hidefix which supports multi-threaded access to HDF5 file (https://github.com/gauteh/hidefix).

Best regards, Gaute

**Comment by adamkewley** [comment]
Hi @gauteh 

I glanced through `zran.c`. It seems (correct me if I'm wrong) to be using an index that indicates when the start of a DEFLATE block is in the compressed data, but it *also* has support for building the look-behind lookup that zlib specifically uses for dictionary lookups?

Statements like:

> An access point can be created at the start of any deflate block, by saving the starting file offset and bit of that block, and the 32K bytes of uncompressed data that precede that block.

`zran.c` indicates that it handles the DEFLATE feature where the data stream can contain multiple concatenated DEFLATE blocks that lookbehind into eachover (it's been a while since I worked in compression, but iirc this could be there to handle the case where there's uncompressed blocks concatenated against blocks with full Huffman encoding etc. - the files I used to work on were mostly entirely independent gzip blocks)

If that's the case, then I'm unsure if `libdeflate` has the necessary feature to do what you need. There's `deflate_decompress` function ([here](https://github.com/adamkewley/libdeflater/blob/master/src/lib.rs#L230)), which will decompress a DEFLATE stream, but I don't think there is s a way to give `libdeflater` a lookbehind to handle the case where elements in the DEFLATE stream back-reference elements in the previous block. You can check for yourself, here:

https://github.com/ebiggers/libdeflate/blob/master/libdeflate.h

These Rust bindings are effectively direct wrappers around the source C API, so if it isn't available in there it will not be available here, either :(

**Comment by gauteh** [comment]
Yes, it seems like this would require a fair bit of work (or at least
figuring out) in libdeflate to make work. Libdeflater performs
significantly better on our use-case, compressed chunks with fixed output
size. It's still the heaviest part of the application. Maybe I can use some
of the other compression libs where the dataset is unchunked. The idea is
that with the decompressor-index it won't be necessary to chunk the
dataset, and thus avoid high read times for queries that only pick a value
in each chunk. But maybe it will be equivalent, since the index must also
be made for chunks.

man. 9. mai 2022, 12:57 skrev Adam Kewley ***@***.***>:
