### ISSUE TITLE
Outstanding chores

### ISSUE THREAD

**Issue by nickbabcock** [adamkewley/libdeflater#23]
I'm relying on this crate more, so let me know if/how one can pitch in to make your life easier / share in responsibility:

- add throughput reporting on benchmark
- enable benchmarks to download data if not present
- add github actions
- rustfmt (I see mention of bindgen in comments, and bindgen automatically invokes rustfmt now, so it seems like even the sys crate should be formatted)
- apply clippy suggestions
- fuzzing? (open to ideas if you had some)
- add benchmark visualizations
- other task you had on your mind

**Comment by adamkewley** [comment]
Thanks for these suggestions.

In terms of which ones I'd focus on, if you wanted to give them a whirl:

- **Add throughput reporting to benchmark**: yes - although the reporting is some hacked-together ruby script or something at the moment, so you may need to play around/change that.
- **Enable benchmarks to download data if not present**: yes - although you'd have to be careful about which URL the codebase locks to and potentially use something like an in-tree hash to validate the corpus (in case the external server changes something)
- **Add GH actions**: yes. Should be a fairly straightforward `cargo test` or similar. Release deployment is currently manual and I'm unsure if it's necessary to automate that part.
- **Rustfmt**: *within reason*. Bindgen isn't used by either `libdeflater` or `libdeflater-sys`. It *was* used at one point but (iirc) the reason I dropped it was because it created an external dependency on `clang` as the frontend parser. You can separately give rustfmt a whirl, as long as it doesn't start doing insanely big, or API-changing, changes.
- **Clippy**: *within reason*. If the suggestions are sane and non-breaking, fine, but there is no major motivation to following all of its suggestions just for the sake of it.
- **Fuzzing**: *no*. Don't bother with fuzzing here. Yes, the `libdeflater` Rust API or C bindings may contain a bug that (e.g.) mis-calculates a C API call into `libdeflate`. That bug may be revealed by fuzzing. However, if you want an *effective* application of fuzzing, I would strongly recommend just working on `libdeflate` itself: it has a much larger user base and a much more complicated implementation (so fuzzing is likely to reveal more there).
- **Benchmark visualizations**: *no*. A basic sorted table is fine for now. This library is a basic low-level wrapper around `libdeflate`. It assumes the users "know what they're getting into" (full-buffer compression /w a specialized zlib implementation), rather than it trying to be a direct competitor to (e.g.) `flate2`. The table is only there to give experienced Rust integrators a rough idea of the performance payoff. I'd recommend improving `libdeflate`'s comparison visualization(s), if that's desired.
- **Other tasks**: none right now. I casually maintain this project and update it whenever something pops up (e.g. a `libdeflate` update). This isn't a library that would benefit from many changes/improvements. Quite the opposite: I deliberately ensure that things don't change very often, because it's a low-level library that will be "buried" into larger codebases (unlike higher-level libraries, that are at the "edges" of integration, and can afford to make more frequent changes without risking recursively screwing many other projects). `libdeflate` is doing all of the actual legwork, I'm just binding to it ;)

**Comment by nickbabcock** [comment]
Thanks so much for a detailed response to each suggestion. I realize now that I may have come off as brash telling you how to run your crate, whereas I was just racking my brain for things you may be desiring but hadn't gotten the time to do.

Sounds like you're all set, and I'd only create more overhead, but feel free to ping me in the future if anything changes 😃
