### ISSUE TITLE
additions to build.rs to support interop with other crates

### ISSUE THREAD

**Issue by pmarks** [adamkewley/libdeflater#3]
@adamkewley cool crate!  @brainstorm and I are looking into adding support for libdeflate to rust-htslib (https://github.com/rust-bio/rust-htslib/). In order for that to work correctly, the build.rs script will need to emit some special lines that will let other crates find the headers of the C code in this crate.  Here's an example for bzip2: https://github.com/alexcrichton/bzip2-rs/blob/master/bzip2-sys/build.rs#L44

I will get a PR together.

**Comment by adamkewley** [comment]
Ah, great! I'm glad you are interested.

I came across libdeflate when working with BAM data (I think htslib C code
uses it), so this should be a good match.

It's a little late for me to look into this tonight but I can read into
what you're saying early next week. If it's an easy enough change and
you're willing to PR it though then that's great also.

**Comment by adamkewley** [comment]
@pmarks just so I understand your goal here, is it that you would like to directly use the C API exposed by libdeflate and, therefore, you would like the C bindings exposed in rust so that you can call the `unsafe` API directly, because you have some specific requirements that this crate doesn't satisfy? If that's the case, then I could roll the [libdeflate_sys.rs](https://github.com/adamkewley/libdeflater/blob/master/src/libdeflate_sys.rs) file internalized in this crate into a separate `libdeflater-sys` crate, which should expose the C FFI API to other devs. It'll take a bit of work, because I'll need to split it into a subcrate, add docs, etc. but I might be able to churn that out in a week.

Or is your requirement specifically that you need to have `libdeflate`s header files on your compiler's include path because you want to compile the `htslib` C code with libdeflate enabled and the compilation command fails because it can't find the necessary include, so you'd like this create to expose the header for that purpose? This might also require creating a `libdeflate-sys` crate, because that's where that kind of thing is "supposed" to be, but just so I understand.

@brainstorm , who asked for a `libdeflate-sys` name for the crate [here](https://github.com/adamkewley/libdeflater/issues/2) might have expected the same thing (that this crate *also* exposes the C API and headers), so I might be able to kill two issues if I roll ahead on this.

**Comment by pmarks** [comment]
@adamkewley my PR (#4) has everything we need to make it work.
The C code in htslib needs to access the C headers of libdeflate, which you can do by:
- Use the `links` directive in Cargo.toml to declare the native library
- emit a `cargo:include=` line, so that downstream crates which can find the C headers exposed by this library. The path returned by this line becomes `DEP_LIBDEFLATE_INCLUDE` [here](https://github.com/rust-bio/rust-htslib/blob/ec97afe19c971cdb42e0eb29a3b8d6107f1af80c/hts-sys/build.rs#L112)

My changes don't _require_ making a `libdeflate-sys` sub-crate, but it's good practice to setup crates like this in that style [see reasons for that style here](https://doc.rust-lang.org/cargo/reference/build-scripts.html#-sys-packages).

**Comment by pmarks** [comment]
and to answer your specific question: we just need the libdeflate headers when we compile the htslib C code. There won't be any Rust code in rust-htslib that calls libdeflate directly.

**Comment by adamkewley** [comment]
Great, thanks for helping me with this information @pmarks. I think that, if I'm being a purist, it feels *wrong* to publish the header + lib paths via `libdeflater`, but I think that, really, the primary goal here is to get you rolling with `htslib-sys`, so I'll quickly spot-check your PR and get it merged to make your downstream experience as easy as possible.

If, later, I get the time to publish `libdeflater-sys`, I'll make sure to PR `htslib-sys` accordingly.

(the "if" is critical, because I'm extremely busy recently and might not ever get around to it ;))

**Comment by pmarks** [comment]
@adamkewley if you're busy, how about I just add libdeflater / libdeflate-sys split into this PR & we can handle it in one shot. Does that sound good to you?

**Comment by adamkewley** [comment]
I'm fairly busy during the week (work + several other things going on). 

I've merged your compiler change etc. that's needed in order for you to move forward with htslib, so you can use that once I publish it (soon). That's not a big deal for me to push out for you, if you have other things to do.

I'd appreciate having `libdeflate-sys`, though, so if you are willing--and, crucially, have the time--then feel free to PR for that. Otherwise, I can try and churn out the changes over the next week or two (again, my time is fairly limited during the evenings). 

My main concern is that being slow on integrating these non-breaking changes is going to block you and waste a bunch of your time, which is why I'm fairly trigger-happy on integrating this (it's non-breaking API change, potentially breaking if people depend on it and `libdeflate-sys` exists, but I reakon you're the only dev dependent on that level).

**Comment by adamkewley** [comment]
@pmarks your change is merged, tagged, and pushed to crates.io as `0.3.0`:

https://crates.io/crates/libdeflater

I hope this helps and, again, thank you for helping with this. Putting the time and effort in to reading the build file, writing an issue, writing a PR etc. is very appreciated.

**Comment by pmarks** [comment]
fixed in #4. separate PR to split into -sys crate in #5 .
