### ISSUE TITLE
Send not implemented for libdeflate_compressor

### ISSUE THREAD

**Issue by rakshith-ravi** [adamkewley/libdeflater#6]
Can't really use this in an async context. The compiler seems to complain about `libdeflate_compressor` not implementing Send. Any idea how I can fix this?

**Comment by IzumiRaine** [comment]
Same for `libdeflater::Decompressor`. Looking at the C code, I'm pretty sure that at least the `Decompressor` should be `Send` (haven't looked much at the compressor yet); the fix would be to add
```
unsafe impl Send for Decompressor { }
```
to the library.

For now, I'm using this (simple but ugly) workaround:
```
struct DecompressorIsSend {
    instance: Decompressor,
}
unsafe impl Send for DecompressorIsSend { }
```

**Comment by adamkewley** [comment]
@rakshith-ravi  @IzumiRaine sorry this has been buried: something about my GitHub/email settings means that I keep missing PRs/issues/mentions - I wasn't actively avoiding the work :D

I can try and implement @IzumiRaine 's suggested fix and get it merged. The only thing I need to double-check is how implementing `Send`, in this case, actually works with raw pointers. The concern being that, because there's no reference-counting, will `Drop` be called twice or is `Send` literally just to support sending the pointer non-atomically to another thread that then takes ownership?

**Comment by IzumiRaine** [comment]
Hi, no worries and thanks for adding this :-)

Some comments about your last question and my understanding of this issue:
- A type being `Send` just tells the compiler that it is safe to create the object in one thread, move it to another thread, and use it there.
(Why might that be problematic at all? E.g. if the object uses thread-local storage. But as far as I understand, almost everything should be `Send` unless there's a specific reason for it.)
- The compiler doesn't know what the raw pointers represent, so it cannot automatically derive `Send`.
- But we can convince ourselves that the C code together with the `libdeflater` Rust interface doesn't depend on what thread we're executing in. This means it is sound to implement `Send`. (the `unsafe` here just means that we proved this ourselves because the compiler can't do it.)
- The problem with `Drop` being called twice can't happen because we can only move the object to another thread but not copy it. (And we can still use the object only in one thread at a time, because we would need the `Sync` trait to do otherwise. But adding `Sync` is definitely problematic without additional synchronization.)

**Comment by adamkewley** [comment]
Ah, thanks for the explanation @IzumiRaine . 

I think I understood `Send` from writing multithreaded stuff previously (e.g. from writing [this](https://github.com/adamkewley/ta-rust)) but I've only, as an occasional Rust user, used it on types that automatically derive it or `std` types (e.g. `Box`, `Arc`). 

My confusion was how moved-from objects work in Rust. In C++, implementing a safe `Decompressor` would be something like:

```c++
class Decompressor {
    libdeflate_decompressor* handle;
public:
    Decompressor() :  handle{libdeflate_alloc_decompressor} {
        if (!handle) {
            throw std::alloc_error{};
        }
    }
    Decompressor(Decompressor&& tmp) : handle{tmp.handle} {
        tmp.handle = nullptr;  // so the moved-from object destructs correctly
    }
    ~Decompressor() noexcept {
        if (handle) {  // necessary, because the moved-from instance in the main thread will be nullptr
            libdeflate_free_decompressor(handle);
        }
    }
    // other ops (copy ctor, assign, etc.)
};
```

Whereas Rust is nicer, in that the compiler completely elides the moved-from object's destructor (C++ doesn't have the concept of use-after-move being strictly forbidden, so the moved-from object must be in a valid destructible state).

This is a very roundabout way of saying "Rust has really nice defaults for handling lifetimes"

**Comment by adamkewley** [comment]
Fixed here: https://github.com/adamkewley/libdeflater/pull/10

**Comment by IzumiRaine** [comment]
@adamkewley Thanks for the comparison to C++, makes sense :)
